spring:
  datasource:
    url: jdbc:mysql://localhost/ibanezdiego
    username: root
    password: WorkPass00
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQL5Dialect
  thymeleaf:
    cache: false